/* =====================================================================
   GAMEDOOR·41 — Sitemap data model
   ~110 pages, 4 niveaux. Tous champs SEO renseignés.
   Champs : url, title, h1, meta, kw (principal + secondaires), intent,
            prio (P0/P1/P2), links (maillage interne)
   silo : home | escape | quiz | action | events | b2b | local | mag |
          reservation | utility | legal | en
   ===================================================================== */

const SILOS = {
  home:        { label: "Home & navigation",       color: "var(--gd-cream)",  short: "HOME" },
  escape:      { label: "Escape Game",             color: "#7A8FB8",          short: "ESC"  },
  quiz:        { label: "Quiz Game",               color: "#9D4EDD",          short: "QZ"   },
  action:      { label: "Action Games",            color: "#BE1B1B",          short: "ACT"  },
  events:      { label: "Events / B2B",            color: "#FFD740",          short: "B2B"  },
  b2b:         { label: "B2B / Privatisations",    color: "#FFD740",          short: "B2B"  },
  local:       { label: "SEO local & matrice",     color: "var(--gd-orange)", short: "LOC"  },
  mag:         { label: "Magazine éditorial",      color: "#F08F45",          short: "MAG"  },
  reservation: { label: "Réservation & contact",   color: "var(--gd-orange)", short: "RDV"  },
  utility:     { label: "Utilitaires & confiance", color: "#C8C2B8",          short: "UTL"  },
  legal:       { label: "Légal",                   color: "#8A8078",          short: "LGL"  },
  en:          { label: "EN sub-tree",             color: "#6A6460",          short: "EN"   },
};

const INTENT_COLORS = {
  transactional: "#E07020",
  informational: "#7A8FB8",
  navigational:  "#C8C2B8",
  commercial:    "#FFD740",
};

/* ------------------------------------------------------------------ */
/* Tree structure. Each node: { id, url, title, h1, meta, kw, kwSec,   */
/* intent, prio, silo, links, children?, note? }                       */
/* ------------------------------------------------------------------ */

const SITEMAP = {
  id: "root",
  url: "https://gamedoor41.fr/",
  title: "GAMEDOOR·41 — Escape Game, Quiz, Action & Events à Caen",
  h1: "GAMEDOOR·41 — Maison du jeu à Caen",
  meta: "Quatre univers de jeu immersif sous un même toit à Mondeville (Caen) : escape game, quiz, action et événementiel premium. Réservez votre créneau.",
  kw: "escape game caen",
  kwSec: ["gamedoor 41", "maison du jeu caen", "loisirs caen", "activité caen"],
  intent: "navigational",
  prio: "P0",
  silo: "home",
  links: ["escape", "quiz", "action", "events", "reserver", "comment-venir"],
  note: "Page d'accueil — silo central. Hero plein écran sur les 4 univers, 3 CTA majeurs.",
  children: [

    /* ================================================================
       1. ESCAPE GAME — silo principal
       ================================================================ */
    {
      id: "escape",
      url: "/escape-game",
      title: "Escape Game à Caen — 3 salles immersives | GAMEDOOR·41",
      h1: "Escape Game à Caen",
      meta: "Trois univers d'escape game à Caen : Psychiatric, Garde à Vue, Back to 80's. Jusqu'à 6 joueurs, 60 minutes, à Mondeville.",
      kw: "escape game caen",
      kwSec: ["escape room caen", "escape game mondeville", "escape game normandie"],
      intent: "commercial",
      prio: "P0",
      silo: "escape",
      links: ["psychiatric", "garde-a-vue", "back-to-80s", "reserver", "comment-venir"],
      note: "Page-pilier silo Escape. Présente les 3 salles + ancrages SEO 'escape game [ville]'.",
      children: [
        {
          id: "psychiatric",
          url: "/escape-game/psychiatric",
          title: "Psychiatric — Escape Game horreur à Caen | GAMEDOOR·41",
          h1: "Psychiatric — l'asile",
          meta: "Salle d'escape game horreur à Caen. Enfermés dans un asile abandonné, 60 minutes pour s'échapper. 2 à 6 joueurs. Réservation en ligne.",
          kw: "escape game horreur caen",
          kwSec: ["escape game peur caen", "salle psychiatric caen", "escape room horreur"],
          intent: "transactional",
          prio: "P0",
          silo: "escape",
          links: ["escape", "reserver", "tarifs", "evjf", "evg", "anniversaire-ado"],
        },
        {
          id: "garde-a-vue",
          url: "/escape-game/garde-a-vue",
          title: "Garde à Vue — Escape Game enquête à Caen | GAMEDOOR·41",
          h1: "Garde à Vue — l'enquête",
          meta: "Salle d'escape game enquête policière à Caen. Résolvez l'affaire avant la garde à vue. 60 minutes, 3 à 6 joueurs.",
          kw: "escape game enquête caen",
          kwSec: ["escape game policier caen", "salle enquête caen", "escape room investigation"],
          intent: "transactional",
          prio: "P0",
          silo: "escape",
          links: ["escape", "reserver", "tarifs", "team-building", "anniversaire-adulte"],
        },
        {
          id: "back-to-80s",
          url: "/escape-game/back-to-80s",
          title: "Back to 80's — Escape Game vintage à Caen | GAMEDOOR·41",
          h1: "Back to 80's — années 80",
          meta: "Salle d'escape game fun aux couleurs des années 80 à Caen. Cassettes, néons, énigmes pop. 60 minutes, 2 à 6 joueurs.",
          kw: "escape game année 80 caen",
          kwSec: ["escape game vintage caen", "escape game famille caen", "salle back to 80s"],
          intent: "transactional",
          prio: "P0",
          silo: "escape",
          links: ["escape", "reserver", "tarifs", "anniversaire-enfant", "anniversaire-ado", "famille"],
        },
        {
          id: "escape-comment-ca-marche",
          url: "/escape-game/comment-ca-marche",
          title: "Comment se déroule un escape game ? | GAMEDOOR·41",
          h1: "Le déroulé d'une partie",
          meta: "Briefing, immersion, énigmes, debrief : découvrez comment se passe une session d'escape game chez GAMEDOOR·41 à Caen.",
          kw: "comment se passe un escape game",
          kwSec: ["déroulé escape game", "première fois escape game", "règles escape game"],
          intent: "informational",
          prio: "P1",
          silo: "escape",
          links: ["escape", "faq", "tarifs", "reserver"],
        },
        {
          id: "escape-debutants",
          url: "/escape-game/premiere-fois",
          title: "Première fois en escape game ? Le guide | GAMEDOOR·41",
          h1: "Vous n'avez jamais fait d'escape game ?",
          meta: "Guide pour les débutants : choix de la salle, niveau de difficulté, ce qu'il faut savoir avant votre première escape room à Caen.",
          kw: "escape game débutant",
          kwSec: ["première escape game", "escape game facile caen", "salle escape débutant"],
          intent: "informational",
          prio: "P1",
          silo: "escape",
          links: ["back-to-80s", "escape", "faq", "comment-ca-marche"],
        },
        {
          id: "escape-difficulte",
          url: "/escape-game/niveaux-de-difficulte",
          title: "Niveaux de difficulté des salles | GAMEDOOR·41",
          h1: "Quelle salle pour vous ?",
          meta: "Comparatif des trois salles d'escape game GAMEDOOR·41 par difficulté, ambiance et nombre de joueurs.",
          kw: "escape game difficile caen",
          kwSec: ["escape game expert caen", "comparatif escape game"],
          intent: "informational",
          prio: "P2",
          silo: "escape",
          links: ["psychiatric", "garde-a-vue", "back-to-80s"],
        },
      ],
    },

    /* ================================================================
       2. QUIZ GAME — silo principal
       ================================================================ */
    {
      id: "quiz",
      url: "/quiz",
      title: "Quiz Game à Caen — Buzz Your Brain | GAMEDOOR·41",
      h1: "Quiz Game — l'esprit Buzz Your Brain",
      meta: "Le quiz interactif made in Caen. Buzzers, écran géant, host en live. 6 à 30 joueurs. Catalogue de thèmes : cinéma, musique, années 80…",
      kw: "quiz game caen",
      kwSec: ["buzz your brain", "quiz interactif caen", "soirée quiz caen"],
      intent: "commercial",
      prio: "P0",
      silo: "quiz",
      links: ["quiz-cinema", "quiz-musique", "quiz-culture-g", "quiz-annees-80", "quiz-pop-culture", "quiz-sport", "reserver"],
      note: "Page-pilier silo Quiz. Catalogue de thèmes en grille, hero avec buzzer animé.",
      children: [
        {
          id: "quiz-cinema",
          url: "/quiz/cinema",
          title: "Quiz Cinéma à Caen | GAMEDOOR·41",
          h1: "Quiz Cinéma",
          meta: "Le quiz cinéma à Caen : répliques cultes, BO, affiches. Buzzers, équipes, host en live. Réservation à partir de 6 joueurs.",
          kw: "quiz cinéma caen",
          kwSec: ["quiz films caen", "soirée quiz cinéma normandie"],
          intent: "transactional",
          prio: "P1",
          silo: "quiz",
          links: ["quiz", "reserver", "evjf", "anniversaire-adulte"],
        },
        {
          id: "quiz-musique",
          url: "/quiz/musique",
          title: "Blind Test Musique à Caen | GAMEDOOR·41",
          h1: "Quiz Musique & Blind Test",
          meta: "Blind test musical à Caen : tous les styles, toutes les époques. 6 à 30 joueurs. Soirée privée ou public.",
          kw: "blind test caen",
          kwSec: ["quiz musique caen", "blind test normandie", "soirée blind test"],
          intent: "transactional",
          prio: "P1",
          silo: "quiz",
          links: ["quiz", "reserver", "evjf", "evg", "soiree-entreprise"],
        },
        {
          id: "quiz-culture-g",
          url: "/quiz/culture-generale",
          title: "Quiz Culture Générale à Caen | GAMEDOOR·41",
          h1: "Quiz Culture Générale",
          meta: "Quiz culture G à Caen : histoire, sciences, géo, actu. Format challenge, équipes, buzzers. À partir de 6 joueurs.",
          kw: "quiz culture générale caen",
          kwSec: ["quiz savoir caen", "quiz challenge caen"],
          intent: "transactional",
          prio: "P1",
          silo: "quiz",
          links: ["quiz", "reserver", "team-building", "seminaire"],
        },
        {
          id: "quiz-annees-80",
          url: "/quiz/annees-80",
          title: "Quiz Années 80 à Caen | GAMEDOOR·41",
          h1: "Quiz Années 80",
          meta: "Quiz spécial années 80 : pubs, séries, tubes, gadgets. Soirée nostalgique à Caen. Idéal anniversaire 40-50 ans.",
          kw: "quiz années 80 caen",
          kwSec: ["soirée années 80 caen", "anniversaire 40 ans caen"],
          intent: "transactional",
          prio: "P1",
          silo: "quiz",
          links: ["quiz", "reserver", "anniversaire-adulte", "back-to-80s"],
        },
        {
          id: "quiz-pop-culture",
          url: "/quiz/pop-culture",
          title: "Quiz Pop Culture & Séries à Caen | GAMEDOOR·41",
          h1: "Quiz Pop Culture",
          meta: "Quiz pop culture, séries, jeux vidéo, mèmes. Format jeune et nerveux. À partir de 6 joueurs.",
          kw: "quiz pop culture caen",
          kwSec: ["quiz séries caen", "quiz geek caen"],
          intent: "transactional",
          prio: "P2",
          silo: "quiz",
          links: ["quiz", "reserver", "evjf", "anniversaire-ado"],
        },
        {
          id: "quiz-sport",
          url: "/quiz/sport",
          title: "Quiz Sport à Caen | GAMEDOOR·41",
          h1: "Quiz Sport",
          meta: "Quiz spécial sport à Caen : foot, rugby, JO, légendes. Pour clubs, asso et soirées entre potes.",
          kw: "quiz sport caen",
          kwSec: ["quiz foot caen", "soirée club sport caen"],
          intent: "transactional",
          prio: "P2",
          silo: "quiz",
          links: ["quiz", "reserver", "evg", "team-building"],
        },
        {
          id: "quiz-comment-ca-marche",
          url: "/quiz/comment-ca-marche",
          title: "Comment se déroule un quiz GAMEDOOR·41 ? | GAMEDOOR·41",
          h1: "Le déroulé d'un quiz",
          meta: "Buzzers, équipes, manches, finale. Découvrez comment se déroule un quiz Buzz Your Brain à Caen.",
          kw: "comment se passe un quiz",
          kwSec: ["déroulé quiz caen", "règles quiz buzzer"],
          intent: "informational",
          prio: "P1",
          silo: "quiz",
          links: ["quiz", "faq", "reserver"],
        },
      ],
    },

    /* ================================================================
       3. ACTION GAMES — silo principal (à venir)
       ================================================================ */
    {
      id: "action",
      url: "/action",
      title: "Action Games à Caen — bientôt | GAMEDOOR·41",
      h1: "Action Games — l'arène du réflexe",
      meta: "Death Eyes et Death Floor : deux expériences action en arrivée à Caen. Inscrivez-vous pour être prévenu de l'ouverture.",
      kw: "action game caen",
      kwSec: ["jeu d'arcade caen", "jeu de réflexe caen", "laser game caen alternative"],
      intent: "commercial",
      prio: "P0",
      silo: "action",
      links: ["death-eyes", "death-floor", "reserver"],
      note: "Hero teaser 'Bientôt'. Formulaire 'Prévenez-moi'. Pages enfants no-index initialement.",
      children: [
        {
          id: "death-eyes",
          url: "/action/death-eyes",
          title: "Death Eyes — Action Game à Caen (à venir) | GAMEDOOR·41",
          h1: "Death Eyes — bientôt",
          meta: "Death Eyes : nouvelle expérience action immersive en arrivée à GAMEDOOR·41 Caen. Inscrivez-vous pour être prévenu.",
          kw: "death eyes caen",
          kwSec: ["nouveau jeu caen", "expérience immersive caen"],
          intent: "informational",
          prio: "P2",
          silo: "action",
          links: ["action", "newsletter"],
          note: "no-index initialement (à activer à l'ouverture).",
        },
        {
          id: "death-floor",
          url: "/action/death-floor",
          title: "Death Floor — Action Game à Caen (à venir) | GAMEDOOR·41",
          h1: "Death Floor — bientôt",
          meta: "Death Floor : nouvelle arène action chez GAMEDOOR·41 Caen. Inscrivez-vous pour être prévenu de l'ouverture.",
          kw: "death floor caen",
          kwSec: ["jeu d'arène caen", "expérience adrénaline caen"],
          intent: "informational",
          prio: "P2",
          silo: "action",
          links: ["action", "newsletter"],
          note: "no-index initialement.",
        },
      ],
    },

    /* ================================================================
       4. EVENTS — silo B2B + occasions privées
       ================================================================ */
    {
      id: "events",
      url: "/events",
      title: "Privatisations & Événements à Caen | GAMEDOOR·41",
      h1: "Vos événements chez GAMEDOOR·41",
      meta: "Privatisations, soirées, EVJF, anniversaires, séminaires : organisez votre événement dans 4 univers de jeu à Caen.",
      kw: "privatisation caen",
      kwSec: ["événement entreprise caen", "soirée privée caen", "lieu événement caen"],
      intent: "commercial",
      prio: "P0",
      silo: "events",
      links: ["entreprises", "evjf", "evg", "anniversaire", "famille", "groupe", "privatisation-totale", "tarifs-groupes"],
      note: "Page-pilier B2B + B2C événements. Section bento avec les 7 sous-pages clés.",
      children: [
        /* --- 4a. ENTREPRISES (B2B pur) --- */
        {
          id: "entreprises",
          url: "/events/entreprises",
          title: "Événements d'entreprise à Caen | GAMEDOOR·41",
          h1: "Pour les entreprises",
          meta: "Séminaires, team building, soirées, afterworks : GAMEDOOR·41 reçoit vos événements d'entreprise à Caen.",
          kw: "événement entreprise caen",
          kwSec: ["soirée entreprise caen", "événementiel professionnel caen"],
          intent: "commercial",
          prio: "P0",
          silo: "b2b",
          links: ["seminaire", "team-building", "soiree-entreprise", "afterwork", "incentive", "tarifs-groupes", "contact-b2b"],
          children: [
            {
              id: "seminaire",
              url: "/events/entreprises/seminaire",
              title: "Séminaire d'entreprise à Caen | GAMEDOOR·41",
              h1: "Séminaire d'entreprise",
              meta: "Salle de séminaire à Caen + activités immersives sur place. Format 1/2 journée ou journée. Devis sous 24h.",
              kw: "séminaire caen",
              kwSec: ["salle séminaire caen", "séminaire normandie", "lieu séminaire caen"],
              intent: "transactional",
              prio: "P0",
              silo: "b2b",
              links: ["entreprises", "tarifs-groupes", "contact-b2b", "team-building"],
            },
            {
              id: "team-building",
              url: "/events/entreprises/team-building",
              title: "Team Building à Caen — Escape, Quiz, Challenge | GAMEDOOR·41",
              h1: "Team Building",
              meta: "Team building original à Caen : escape game, quiz inter-équipes, challenge multi-univers. 10 à 80 collaborateurs.",
              kw: "team building caen",
              kwSec: ["team building normandie", "cohésion d'équipe caen", "activité team building caen"],
              intent: "transactional",
              prio: "P0",
              silo: "b2b",
              links: ["entreprises", "tarifs-groupes", "contact-b2b", "incentive", "seminaire"],
            },
            {
              id: "soiree-entreprise",
              url: "/events/entreprises/soiree-entreprise",
              title: "Soirée d'entreprise à Caen | GAMEDOOR·41",
              h1: "Soirée d'entreprise",
              meta: "Soirée d'entreprise privatisée à Caen : quiz, blind test, escape game, ambiance bar. Jusqu'à 80 personnes.",
              kw: "soirée entreprise caen",
              kwSec: ["soirée d'entreprise normandie", "soirée fin d'année caen"],
              intent: "transactional",
              prio: "P1",
              silo: "b2b",
              links: ["entreprises", "afterwork", "privatisation-totale", "contact-b2b"],
            },
            {
              id: "afterwork",
              url: "/events/entreprises/afterwork",
              title: "Afterwork à Caen | GAMEDOOR·41",
              h1: "Afterwork",
              meta: "Format afterwork : 2h, quiz, jeu, drink. Idéal pour collègues à Caen. À partir de 10 personnes.",
              kw: "afterwork caen",
              kwSec: ["afterwork entreprise caen", "soirée collègues caen"],
              intent: "transactional",
              prio: "P1",
              silo: "b2b",
              links: ["entreprises", "soiree-entreprise", "contact-b2b"],
            },
            {
              id: "incentive",
              url: "/events/entreprises/incentive",
              title: "Incentive & Récompense d'équipe à Caen | GAMEDOOR·41",
              h1: "Incentive",
              meta: "Format incentive premium à Caen : récompense d'équipe, journée immersive, sur-mesure. Devis dédié.",
              kw: "incentive caen",
              kwSec: ["récompense équipe caen", "événement incentive normandie"],
              intent: "transactional",
              prio: "P2",
              silo: "b2b",
              links: ["entreprises", "team-building", "contact-b2b"],
            },
            {
              id: "tarifs-groupes",
              url: "/events/entreprises/tarifs-et-formules",
              title: "Tarifs & formules entreprises | GAMEDOOR·41",
              h1: "Tarifs entreprises",
              meta: "Grille tarifaire pour groupes et entreprises : escape game, quiz, privatisation totale. Devis personnalisé sous 24h.",
              kw: "tarif team building caen",
              kwSec: ["prix séminaire caen", "devis événement entreprise caen"],
              intent: "transactional",
              prio: "P1",
              silo: "b2b",
              links: ["entreprises", "contact-b2b", "tarifs"],
            },
            {
              id: "contact-b2b",
              url: "/events/entreprises/devis",
              title: "Demande de devis entreprises | GAMEDOOR·41",
              h1: "Demande de devis",
              meta: "Formulaire dédié entreprises. Devis personnalisé sous 24h, contact direct chargé événementiel.",
              kw: "devis team building caen",
              kwSec: ["devis séminaire caen", "demande événement entreprise"],
              intent: "transactional",
              prio: "P0",
              silo: "b2b",
              links: ["entreprises", "tarifs-groupes"],
            },
          ],
        },

        /* --- 4b. ÉVÉNEMENTS PRIVÉS --- */
        {
          id: "evjf",
          url: "/events/evjf",
          title: "EVJF à Caen — Enterrement de Vie de Jeune Fille | GAMEDOOR·41",
          h1: "EVJF — l'EVJF qui sort de l'ordinaire",
          meta: "EVJF original à Caen : escape game peur, blind test, soirée privée. Formule 100% sur-mesure de 4 à 12 copines.",
          kw: "evjf caen",
          kwSec: ["enterrement vie jeune fille caen", "evjf normandie", "evjf original caen"],
          intent: "transactional",
          prio: "P0",
          silo: "events",
          links: ["events", "psychiatric", "quiz-musique", "tarifs-groupes", "reserver"],
        },
        {
          id: "evg",
          url: "/events/evg",
          title: "EVG à Caen — Enterrement de Vie de Garçon | GAMEDOOR·41",
          h1: "EVG — l'EVG qu'on raconte",
          meta: "EVG original à Caen : escape game enquête, quiz, défi inter-univers. 4 à 12 potes, formule sur-mesure.",
          kw: "evg caen",
          kwSec: ["enterrement vie garçon caen", "evg normandie", "evg original caen"],
          intent: "transactional",
          prio: "P0",
          silo: "events",
          links: ["events", "garde-a-vue", "quiz-sport", "tarifs-groupes", "reserver"],
        },
        {
          id: "anniversaire",
          url: "/events/anniversaire",
          title: "Anniversaire à Caen — Escape, Quiz, Action | GAMEDOOR·41",
          h1: "Anniversaires",
          meta: "Fêtez votre anniversaire à GAMEDOOR·41 Caen : escape game, quiz, formules enfant, ado, adulte.",
          kw: "anniversaire caen",
          kwSec: ["fête anniversaire caen", "lieu anniversaire caen", "anniversaire original caen"],
          intent: "commercial",
          prio: "P0",
          silo: "events",
          links: ["anniversaire-enfant", "anniversaire-ado", "anniversaire-adulte", "events"],
          children: [
            {
              id: "anniversaire-enfant",
              url: "/events/anniversaire/enfant",
              title: "Anniversaire enfant 8-12 ans à Caen | GAMEDOOR·41",
              h1: "Anniversaire enfant (8-12 ans)",
              meta: "Anniversaire enfant à Caen : escape game Back to 80's adapté, quiz junior. Formule clé en main, gâteau possible.",
              kw: "anniversaire enfant caen",
              kwSec: ["anniversaire 10 ans caen", "anniversaire enfant original caen", "escape game enfant caen"],
              intent: "transactional",
              prio: "P0",
              silo: "events",
              links: ["back-to-80s", "anniversaire", "tarifs", "reserver"],
            },
            {
              id: "anniversaire-ado",
              url: "/events/anniversaire/ado",
              title: "Anniversaire ado 13-17 ans à Caen | GAMEDOOR·41",
              h1: "Anniversaire ado (13-17 ans)",
              meta: "Anniversaire ado à Caen : escape game horreur ou enquête, quiz pop culture. Formule clé en main.",
              kw: "anniversaire ado caen",
              kwSec: ["anniversaire 15 ans caen", "anniversaire 16 ans caen", "escape game ado caen"],
              intent: "transactional",
              prio: "P1",
              silo: "events",
              links: ["psychiatric", "quiz-pop-culture", "anniversaire", "reserver"],
            },
            {
              id: "anniversaire-adulte",
              url: "/events/anniversaire/adulte",
              title: "Anniversaire adulte à Caen | GAMEDOOR·41",
              h1: "Anniversaire adulte",
              meta: "Anniversaire adulte à Caen : 30, 40, 50 ans. Escape, quiz années 80, soirée privatisée jusqu'à 30 personnes.",
              kw: "anniversaire 40 ans caen",
              kwSec: ["anniversaire 30 ans caen", "anniversaire 50 ans caen", "soirée anniversaire caen"],
              intent: "transactional",
              prio: "P0",
              silo: "events",
              links: ["quiz-annees-80", "garde-a-vue", "anniversaire", "reserver"],
            },
          ],
        },
        {
          id: "famille",
          url: "/events/famille",
          title: "Sortie famille à Caen | GAMEDOOR·41",
          h1: "En famille",
          meta: "Sortie famille à Caen : escape game adapté dès 10 ans, quiz familial. Idéal week-end pluvieux ou vacances.",
          kw: "sortie famille caen",
          kwSec: ["activité famille caen", "que faire en famille caen", "loisirs famille normandie"],
          intent: "commercial",
          prio: "P1",
          silo: "events",
          links: ["back-to-80s", "events", "anniversaire-enfant", "reserver"],
        },
        {
          id: "groupe",
          url: "/events/groupes",
          title: "Sortie de groupe à Caen | GAMEDOOR·41",
          h1: "Groupes & associations",
          meta: "Sortie groupe à Caen : asso, club, CE, comité d'entreprise. À partir de 10 personnes, tarifs dégressifs.",
          kw: "sortie groupe caen",
          kwSec: ["sortie ce caen", "sortie association caen", "sortie club caen"],
          intent: "commercial",
          prio: "P1",
          silo: "events",
          links: ["events", "tarifs-groupes", "team-building", "contact-b2b"],
        },
        {
          id: "privatisation-totale",
          url: "/events/privatisation-totale",
          title: "Privatisation totale du complexe à Caen | GAMEDOOR·41",
          h1: "Privatisation totale",
          meta: "Privatisez les 1500m² de GAMEDOOR·41 à Caen : 4 univers, jusqu'à 80 personnes. Formule premium sur devis.",
          kw: "privatisation caen",
          kwSec: ["privatiser lieu caen", "événement privé caen", "lieu atypique caen"],
          intent: "transactional",
          prio: "P0",
          silo: "events",
          links: ["events", "soiree-entreprise", "contact-b2b", "tarifs-groupes"],
        },
      ],
    },

    /* ================================================================
       5. RÉSERVATION & TARIFS
       ================================================================ */
    {
      id: "reserver",
      url: "/reserver",
      title: "Réserver votre séance | GAMEDOOR·41",
      h1: "Réservez votre créneau",
      meta: "Choisissez votre univers, votre salle et votre créneau. Réservation en ligne sécurisée — paiement via Bookeo.",
      kw: "réserver escape game caen",
      kwSec: ["réservation escape game caen", "réserver quiz caen", "billet escape game caen"],
      intent: "transactional",
      prio: "P0",
      silo: "reservation",
      links: ["escape", "quiz", "events", "tarifs", "comment-venir"],
      note: "Hub de redirection vers Bookeo (lien sortant). Pas de tunnel propre — un seul lien externe par univers/salle.",
    },
    {
      id: "tarifs",
      url: "/tarifs",
      title: "Tarifs Escape Game, Quiz & Events à Caen | GAMEDOOR·41",
      h1: "Nos tarifs",
      meta: "Grille tarifaire transparente : escape game à partir de 25€/joueur, quiz à partir de 18€/joueur. Tarifs groupes & entreprises.",
      kw: "tarif escape game caen",
      kwSec: ["prix escape game caen", "tarif quiz caen", "prix séminaire caen"],
      intent: "commercial",
      prio: "P0",
      silo: "reservation",
      links: ["reserver", "escape", "quiz", "tarifs-groupes", "cartes-cadeaux"],
    },
    {
      id: "cartes-cadeaux",
      url: "/cartes-cadeaux",
      title: "Cartes cadeaux Escape, Quiz & Events | GAMEDOOR·41",
      h1: "Offrez du jeu",
      meta: "Cartes cadeaux GAMEDOOR·41 : escape game, quiz, événements. Valable 1 an, livraison instantanée par email.",
      kw: "carte cadeau escape game caen",
      kwSec: ["bon cadeau escape game caen", "idée cadeau caen", "cadeau original caen"],
      intent: "transactional",
      prio: "P0",
      silo: "reservation",
      links: ["reserver", "tarifs", "escape", "quiz"],
    },

    /* ================================================================
       6. SEO LOCAL — matrice [activité × ville] + [activité × occasion]
       ================================================================ */
    {
      id: "local-hub",
      url: "/ou-jouer",
      title: "Où jouer en Normandie ? | GAMEDOOR·41",
      h1: "GAMEDOOR·41 en Normandie",
      meta: "Notre complexe se trouve à Mondeville, à 5 min de Caen centre. Découvrez les bons plans selon votre ville en Normandie.",
      kw: "escape game normandie",
      kwSec: ["loisirs normandie", "que faire normandie"],
      intent: "informational",
      prio: "P1",
      silo: "local",
      links: ["loc-caen", "loc-mondeville", "loc-herouville", "loc-bayeux", "loc-lisieux", "loc-cherbourg", "comment-venir"],
      note: "Hub de la matrice locale. Le complexe physique reste à Mondeville — toutes les pages locales redirigent vers /reserver.",
      children: [
        /* === Pages [ville] (ancrage géographique) === */
        {
          id: "loc-caen",
          url: "/ou-jouer/caen",
          title: "Escape Game, Quiz & Events à Caen | GAMEDOOR·41",
          h1: "GAMEDOOR·41 — votre maison du jeu à Caen",
          meta: "Le complexe de jeu n°1 à Caen : 3 escape games, quiz Buzz Your Brain, events. À 5 min du centre, parking gratuit.",
          kw: "escape game caen",
          kwSec: ["activité caen", "loisirs caen", "que faire caen", "sortie caen"],
          intent: "commercial",
          prio: "P0",
          silo: "local",
          links: ["escape", "quiz", "events", "comment-venir", "reserver"],
        },
        {
          id: "loc-mondeville",
          url: "/ou-jouer/mondeville",
          title: "Escape Game, Quiz à Mondeville | GAMEDOOR·41",
          h1: "GAMEDOOR·41 à Mondeville",
          meta: "GAMEDOOR·41 est implanté au 41 bis rue Pasteur à Mondeville (14120) — 1500m² dédiés au jeu.",
          kw: "escape game mondeville",
          kwSec: ["loisirs mondeville", "activité mondeville", "que faire mondeville"],
          intent: "commercial",
          prio: "P0",
          silo: "local",
          links: ["loc-caen", "comment-venir", "escape", "quiz"],
        },
        {
          id: "loc-herouville",
          url: "/ou-jouer/herouville-saint-clair",
          title: "Escape Game près d'Hérouville-Saint-Clair | GAMEDOOR·41",
          h1: "Pour les Hérouvillais",
          meta: "À 10 min d'Hérouville-Saint-Clair, GAMEDOOR·41 propose escape game, quiz et events à Mondeville.",
          kw: "escape game hérouville saint clair",
          kwSec: ["loisirs hérouville", "que faire hérouville saint clair"],
          intent: "commercial",
          prio: "P1",
          silo: "local",
          links: ["loc-caen", "comment-venir", "escape", "quiz"],
        },
        {
          id: "loc-bayeux",
          url: "/ou-jouer/bayeux",
          title: "Escape Game près de Bayeux | GAMEDOOR·41",
          h1: "Pour les Bajocasses",
          meta: "À 30 min de Bayeux, GAMEDOOR·41 vous accueille à Mondeville. Idéal sortie famille ou afterwork.",
          kw: "escape game bayeux",
          kwSec: ["loisirs bayeux", "que faire bayeux"],
          intent: "commercial",
          prio: "P1",
          silo: "local",
          links: ["loc-caen", "comment-venir", "escape"],
        },
        {
          id: "loc-lisieux",
          url: "/ou-jouer/lisieux",
          title: "Escape Game près de Lisieux | GAMEDOOR·41",
          h1: "Pour les Lexoviens",
          meta: "À 40 min de Lisieux, GAMEDOOR·41 propose 4 univers de jeu à Mondeville.",
          kw: "escape game lisieux",
          kwSec: ["loisirs lisieux", "que faire lisieux"],
          intent: "commercial",
          prio: "P2",
          silo: "local",
          links: ["loc-caen", "comment-venir", "escape"],
        },
        {
          id: "loc-cherbourg",
          url: "/ou-jouer/cherbourg",
          title: "Escape Game près de Cherbourg | GAMEDOOR·41",
          h1: "Pour les Cherbourgeois",
          meta: "À 1h20 de Cherbourg, GAMEDOOR·41 vous accueille à Mondeville. Idéal séminaire ou week-end Caen.",
          kw: "escape game cherbourg",
          kwSec: ["loisirs cherbourg", "team building cherbourg"],
          intent: "commercial",
          prio: "P2",
          silo: "local",
          links: ["loc-caen", "seminaire", "comment-venir"],
        },
        /* === Pages [activité × ville] (matrice profonde) === */
        {
          id: "matrix-evjf-caen",
          url: "/ou-jouer/caen/evjf",
          title: "EVJF à Caen — formule complète | GAMEDOOR·41",
          h1: "EVJF à Caen",
          meta: "Tout pour votre EVJF à Caen : escape game peur, blind test, soirée privée chez GAMEDOOR·41 (Mondeville, 5 min de Caen).",
          kw: "evjf caen",
          kwSec: ["enterrement vie jeune fille caen", "evjf original caen"],
          intent: "transactional",
          prio: "P0",
          silo: "local",
          links: ["evjf", "loc-caen", "psychiatric", "quiz-musique"],
          note: "Doublon SEO légitime avec /events/evjf — angle géographique vs angle occasion.",
        },
        {
          id: "matrix-team-building-caen",
          url: "/ou-jouer/caen/team-building",
          title: "Team Building à Caen — l'idée originale | GAMEDOOR·41",
          h1: "Team Building à Caen",
          meta: "Le team building qui sort des bowlings : escape, quiz, défi multi-univers à 5 min de Caen.",
          kw: "team building caen",
          kwSec: ["team building normandie", "cohésion équipe caen"],
          intent: "transactional",
          prio: "P0",
          silo: "local",
          links: ["team-building", "loc-caen", "seminaire", "contact-b2b"],
        },
        {
          id: "matrix-seminaire-caen",
          url: "/ou-jouer/caen/seminaire",
          title: "Séminaire à Caen — lieu atypique | GAMEDOOR·41",
          h1: "Séminaire à Caen",
          meta: "Lieu de séminaire atypique à Caen : 1500m², 4 univers, salle plénière, restauration sur place.",
          kw: "séminaire caen",
          kwSec: ["lieu séminaire caen", "salle séminaire caen"],
          intent: "transactional",
          prio: "P0",
          silo: "local",
          links: ["seminaire", "loc-caen", "team-building", "contact-b2b"],
        },
        {
          id: "matrix-anniv-caen",
          url: "/ou-jouer/caen/anniversaire",
          title: "Anniversaire à Caen — l'idée qui change | GAMEDOOR·41",
          h1: "Anniversaire à Caen",
          meta: "Fêtez votre anniversaire à Caen autrement : escape game, quiz, événement privatisé. Enfants, ados, adultes.",
          kw: "anniversaire caen",
          kwSec: ["lieu anniversaire caen", "anniversaire original caen"],
          intent: "transactional",
          prio: "P0",
          silo: "local",
          links: ["anniversaire", "loc-caen", "back-to-80s", "quiz-annees-80"],
        },
        {
          id: "matrix-evg-caen",
          url: "/ou-jouer/caen/evg",
          title: "EVG à Caen — formule originale | GAMEDOOR·41",
          h1: "EVG à Caen",
          meta: "EVG à Caen : escape enquête, quiz sport, soirée privée. À partir de 4 personnes.",
          kw: "evg caen",
          kwSec: ["enterrement vie garçon caen", "evg normandie"],
          intent: "transactional",
          prio: "P0",
          silo: "local",
          links: ["evg", "loc-caen", "garde-a-vue", "quiz-sport"],
        },
        {
          id: "matrix-tb-cherbourg",
          url: "/ou-jouer/cherbourg/team-building",
          title: "Team Building Cherbourg — l'option Caen | GAMEDOOR·41",
          h1: "Team Building pour Cherbourg",
          meta: "À 1h20 de Cherbourg, le complexe GAMEDOOR·41 organise vos team buildings : escape, quiz, défi.",
          kw: "team building cherbourg",
          kwSec: ["team building manche", "incentive cherbourg"],
          intent: "transactional",
          prio: "P2",
          silo: "local",
          links: ["team-building", "loc-cherbourg", "seminaire"],
        },
      ],
    },

    /* ================================================================
       7. MAGAZINE — blog éditorial
       ================================================================ */
    {
      id: "magazine",
      url: "/magazine",
      title: "Magazine GAMEDOOR·41 — guides, actus & coulisses",
      h1: "Magazine",
      meta: "Le magazine GAMEDOOR·41 : guides pour bien choisir, actus du complexe, coulisses des salles. Tout l'esprit maison du jeu à Caen.",
      kw: "blog escape game caen",
      kwSec: ["magazine loisirs caen", "guide escape game caen"],
      intent: "informational",
      prio: "P1",
      silo: "mag",
      links: ["mag-guides", "mag-actus", "mag-coulisses", "mag-glossaire"],
      note: "Hub de magazine, pagination par catégorie. ~30-50 articles à terme.",
      children: [
        /* --- 7a. GUIDES (cat) --- */
        {
          id: "mag-guides",
          url: "/magazine/guides",
          title: "Guides — bien choisir son escape game à Caen | GAMEDOOR·41",
          h1: "Guides",
          meta: "Tous nos guides pour bien choisir votre escape game, quiz ou événement à Caen.",
          kw: "guide escape game caen",
          kwSec: ["choisir escape game caen", "tutoriel escape game"],
          intent: "informational",
          prio: "P1",
          silo: "mag",
          links: ["magazine", "guide-debutants", "guide-evjf", "guide-team-building", "guide-anniversaire"],
          children: [
            {
              id: "guide-debutants",
              url: "/magazine/guides/escape-game-debutant-caen",
              title: "Escape Game pour débutants à Caen — le guide | GAMEDOOR·41",
              h1: "Escape Game pour débutants : par où commencer ?",
              meta: "Vous n'avez jamais fait d'escape game ? Voici comment choisir votre première salle à Caen sans stress.",
              kw: "escape game débutant caen",
              kwSec: ["première fois escape game", "escape game facile caen"],
              intent: "informational",
              prio: "P1",
              silo: "mag",
              links: ["back-to-80s", "escape", "mag-guides", "escape-debutants"],
            },
            {
              id: "guide-evjf",
              url: "/magazine/guides/idees-evjf-caen-normandie",
              title: "10 idées d'EVJF à Caen et en Normandie | GAMEDOOR·41",
              h1: "10 idées d'EVJF à Caen et en Normandie",
              meta: "Notre sélection de 10 idées originales pour un EVJF mémorable à Caen et en Normandie.",
              kw: "idée evjf caen",
              kwSec: ["evjf normandie idée", "que faire evjf caen"],
              intent: "informational",
              prio: "P1",
              silo: "mag",
              links: ["evjf", "matrix-evjf-caen", "psychiatric", "mag-guides"],
            },
            {
              id: "guide-team-building",
              url: "/magazine/guides/team-building-original-caen",
              title: "Team Building original à Caen : le top 7 | GAMEDOOR·41",
              h1: "Team Building original à Caen : le top 7",
              meta: "Au-delà du paintball et du karting : 7 idées de team building qui marquent vraiment, à Caen.",
              kw: "team building original caen",
              kwSec: ["activité team building caen", "team building insolite caen"],
              intent: "informational",
              prio: "P1",
              silo: "mag",
              links: ["team-building", "matrix-team-building-caen", "seminaire", "mag-guides"],
            },
            {
              id: "guide-anniversaire",
              url: "/magazine/guides/anniversaire-original-caen",
              title: "Anniversaire original à Caen : 8 idées | GAMEDOOR·41",
              h1: "Anniversaire original à Caen",
              meta: "8 idées d'anniversaire originaux à Caen pour enfants, ados et adultes.",
              kw: "anniversaire original caen",
              kwSec: ["fête anniversaire caen", "anniversaire 30 ans caen"],
              intent: "informational",
              prio: "P1",
              silo: "mag",
              links: ["anniversaire", "anniversaire-enfant", "anniversaire-adulte", "mag-guides"],
            },
            {
              id: "guide-quiz",
              url: "/magazine/guides/comment-organiser-un-quiz-soiree",
              title: "Comment organiser une soirée quiz mémorable | GAMEDOOR·41",
              h1: "Organiser une soirée quiz : le mode d'emploi",
              meta: "Buzzers, host, formats, thèmes : le guide complet pour réussir votre soirée quiz à Caen.",
              kw: "organiser soirée quiz",
              kwSec: ["soirée quiz caen", "quiz buzzer caen"],
              intent: "informational",
              prio: "P2",
              silo: "mag",
              links: ["quiz", "quiz-comment-ca-marche", "mag-guides"],
            },
          ],
        },
        /* --- 7b. ACTUS (cat) --- */
        {
          id: "mag-actus",
          url: "/magazine/actus",
          title: "Actus GAMEDOOR·41 — nouveautés à Caen | GAMEDOOR·41",
          h1: "Actus",
          meta: "Toutes les nouveautés de GAMEDOOR·41 à Caen : nouvelles salles, événements, partenariats.",
          kw: "actu escape game caen",
          kwSec: ["nouveauté escape game caen"],
          intent: "informational",
          prio: "P2",
          silo: "mag",
          links: ["magazine", "actu-fusion", "actu-action", "actu-saint-valentin", "actu-halloween"],
          children: [
            {
              id: "actu-fusion",
              url: "/magazine/actus/naissance-gamedoor-41",
              title: "Naissance de GAMEDOOR·41 : la fusion Brain Escape & Buzz Your Brain",
              h1: "GAMEDOOR·41 — l'histoire d'une fusion",
              meta: "En 2026, Brain Escape Game et Buzz Your Brain fusionnent pour créer GAMEDOOR·41, la maison du jeu à Caen.",
              kw: "gamedoor 41 ouverture",
              kwSec: ["fusion brain escape buzz your brain", "nouveau complexe caen"],
              intent: "informational",
              prio: "P1",
              silo: "mag",
              links: ["a-propos", "magazine", "mag-actus"],
            },
            {
              id: "actu-action",
              url: "/magazine/actus/death-eyes-death-floor-arrivee",
              title: "Death Eyes & Death Floor : ouverture imminente | GAMEDOOR·41",
              h1: "Death Eyes & Death Floor arrivent",
              meta: "Deux nouveaux univers Action arrivent à GAMEDOOR·41 Caen : Death Eyes et Death Floor.",
              kw: "death eyes caen",
              kwSec: ["nouveauté gamedoor 41", "action game caen"],
              intent: "informational",
              prio: "P2",
              silo: "mag",
              links: ["action", "death-eyes", "death-floor", "mag-actus"],
            },
            {
              id: "actu-saint-valentin",
              url: "/magazine/actus/saint-valentin-caen-2026",
              title: "Saint-Valentin originale à Caen 2026 | GAMEDOOR·41",
              h1: "Saint-Valentin à Caen : sortez du resto",
              meta: "Une Saint-Valentin originale à Caen : escape en duo, quiz romantique, formule clé en main.",
              kw: "saint valentin caen",
              kwSec: ["sortie saint valentin caen", "idée saint valentin caen"],
              intent: "commercial",
              prio: "P2",
              silo: "mag",
              links: ["escape", "quiz", "loc-caen", "mag-actus"],
            },
            {
              id: "actu-halloween",
              url: "/magazine/actus/halloween-caen",
              title: "Halloween à Caen : la nuit Psychiatric | GAMEDOOR·41",
              h1: "Halloween à Caen",
              meta: "Halloween à GAMEDOOR·41 Caen : nuit Psychiatric, déguisements, quiz horreur.",
              kw: "halloween caen",
              kwSec: ["soirée halloween caen", "escape halloween caen"],
              intent: "commercial",
              prio: "P2",
              silo: "mag",
              links: ["psychiatric", "loc-caen", "mag-actus"],
            },
          ],
        },
        /* --- 7c. COULISSES (cat) --- */
        {
          id: "mag-coulisses",
          url: "/magazine/coulisses",
          title: "Coulisses — la fabrique d'un escape game | GAMEDOOR·41",
          h1: "Coulisses",
          meta: "Comment on imagine, construit et fait vivre les salles de GAMEDOOR·41 à Caen.",
          kw: "coulisses escape game",
          kwSec: ["fabrication escape game", "comment crée-t-on un escape game"],
          intent: "informational",
          prio: "P2",
          silo: "mag",
          links: ["magazine", "coul-creation", "coul-game-master", "coul-equipe"],
          children: [
            {
              id: "coul-creation",
              url: "/magazine/coulisses/creation-salle-psychiatric",
              title: "Comment on a créé Psychiatric | GAMEDOOR·41",
              h1: "La fabrique de Psychiatric",
              meta: "Behind the scenes : 14 mois de scénographie, prototypage, tests pour donner vie à Psychiatric.",
              kw: "création escape game",
              kwSec: ["psychiatric coulisses", "scénographie escape game"],
              intent: "informational",
              prio: "P2",
              silo: "mag",
              links: ["psychiatric", "mag-coulisses"],
            },
            {
              id: "coul-game-master",
              url: "/magazine/coulisses/metier-de-game-master",
              title: "Le métier de Game Master | GAMEDOOR·41",
              h1: "Game Master, ce métier",
              meta: "Plongée dans la cabine : qui sont les Game Masters de GAMEDOOR·41 et que font-ils vraiment ?",
              kw: "métier game master",
              kwSec: ["game master caen", "recrutement escape game caen"],
              intent: "informational",
              prio: "P2",
              silo: "mag",
              links: ["recrutement", "mag-coulisses"],
            },
            {
              id: "coul-equipe",
              url: "/magazine/coulisses/lequipe-gamedoor-41",
              title: "L'équipe GAMEDOOR·41 | GAMEDOOR·41",
              h1: "Les visages de GAMEDOOR·41",
              meta: "Allan, Marion, Tom et toute l'équipe qui anime votre maison du jeu à Caen.",
              kw: "équipe gamedoor 41",
              kwSec: ["allan boehme", "équipe escape game caen"],
              intent: "informational",
              prio: "P2",
              silo: "mag",
              links: ["a-propos", "recrutement", "mag-coulisses"],
            },
          ],
        },
        /* --- 7d. GLOSSAIRE (cat) --- */
        {
          id: "mag-glossaire",
          url: "/magazine/glossaire",
          title: "Glossaire de l'escape game et du quiz | GAMEDOOR·41",
          h1: "Glossaire",
          meta: "Tous les termes du jeu en salle expliqués simplement : game master, débrief, indice, énigme, buzzer…",
          kw: "lexique escape game",
          kwSec: ["vocabulaire escape game", "termes escape game"],
          intent: "informational",
          prio: "P2",
          silo: "mag",
          links: ["magazine", "mag-guides"],
        },
      ],
    },

    /* ================================================================
       8. CONFIANCE & UTILITAIRES
       ================================================================ */
    {
      id: "a-propos",
      url: "/a-propos",
      title: "À propos — GAMEDOOR·41 | Maison du jeu à Caen",
      h1: "On est qui, on est où",
      meta: "L'histoire de GAMEDOOR·41, fusion en 2026 de Brain Escape Game et Buzz Your Brain. Notre maison du jeu à Caen.",
      kw: "gamedoor 41 histoire",
      kwSec: ["allan boehme", "brain escape game caen", "buzz your brain caen"],
      intent: "informational",
      prio: "P1",
      silo: "utility",
      links: ["actu-fusion", "coul-equipe", "recrutement", "presse"],
    },
    {
      id: "comment-venir",
      url: "/acces",
      title: "Adresse, parking & accès | GAMEDOOR·41 Caen",
      h1: "Comment venir",
      meta: "41 bis rue Pasteur, 14120 Mondeville. À 5 min de Caen, parking gratuit, accès tram T1 + bus, PMR.",
      kw: "gamedoor 41 adresse",
      kwSec: ["parking caen mondeville", "tram caen mondeville", "accès gamedoor 41"],
      intent: "navigational",
      prio: "P0",
      silo: "utility",
      links: ["loc-caen", "loc-mondeville", "accessibilite", "reserver", "contact"],
    },
    {
      id: "accessibilite",
      url: "/accessibilite",
      title: "Accessibilité PMR | GAMEDOOR·41",
      h1: "Accessibilité",
      meta: "GAMEDOOR·41 est accessible aux personnes à mobilité réduite : ascenseur, sanitaires PMR, salles adaptées.",
      kw: "escape game accessible pmr",
      kwSec: ["escape game handicap caen", "loisirs pmr caen"],
      intent: "informational",
      prio: "P1",
      silo: "utility",
      links: ["comment-venir", "contact", "faq"],
    },
    {
      id: "faq",
      url: "/faq",
      title: "FAQ — Questions fréquentes | GAMEDOOR·41",
      h1: "Questions fréquentes",
      meta: "Toutes les réponses sur l'escape game, le quiz, les events, les tarifs et l'accès chez GAMEDOOR·41 à Caen.",
      kw: "faq escape game caen",
      kwSec: ["question escape game", "comment ça marche escape game"],
      intent: "informational",
      prio: "P0",
      silo: "utility",
      links: ["escape", "quiz", "events", "tarifs", "comment-venir", "accessibilite"],
    },
    {
      id: "avis",
      url: "/avis",
      title: "Avis clients — ils ont joué chez nous | GAMEDOOR·41",
      h1: "Ils ont joué chez nous",
      meta: "Les avis vérifiés de nos joueurs : escape game, quiz, séminaires, EVJF, anniversaires à GAMEDOOR·41 Caen.",
      kw: "avis escape game caen",
      kwSec: ["avis quiz caen", "témoignage escape game caen"],
      intent: "commercial",
      prio: "P1",
      silo: "utility",
      links: ["escape", "quiz", "events", "reserver"],
    },
    {
      id: "recrutement",
      url: "/on-recrute",
      title: "On recrute — rejoignez GAMEDOOR·41 | GAMEDOOR·41",
      h1: "On recrute",
      meta: "Game Master, animateur quiz, événementiel, accueil : rejoignez GAMEDOOR·41 à Caen. Postes en CDI, CDD, alternance.",
      kw: "recrutement escape game caen",
      kwSec: ["job game master caen", "emploi loisirs caen"],
      intent: "navigational",
      prio: "P1",
      silo: "utility",
      links: ["a-propos", "coul-game-master", "contact"],
    },
    {
      id: "presse",
      url: "/presse",
      title: "Espace presse | GAMEDOOR·41",
      h1: "Presse",
      meta: "Communiqués, kit presse, photos HD : tout pour parler de GAMEDOOR·41 à Caen.",
      kw: "gamedoor 41 presse",
      kwSec: ["communiqué presse escape game caen"],
      intent: "navigational",
      prio: "P2",
      silo: "utility",
      links: ["a-propos", "actu-fusion", "contact"],
    },
    {
      id: "contact",
      url: "/contact",
      title: "Contact | GAMEDOOR·41",
      h1: "Nous écrire",
      meta: "Une question, un projet, une demande presse ? Écrivez-nous ou appelez-nous : 41 bis rue Pasteur, Mondeville.",
      kw: "contact gamedoor 41",
      kwSec: ["téléphone gamedoor 41", "email escape game caen"],
      intent: "navigational",
      prio: "P0",
      silo: "utility",
      links: ["contact-b2b", "comment-venir", "faq"],
    },
    {
      id: "newsletter",
      url: "/newsletter",
      title: "Newsletter | GAMEDOOR·41",
      h1: "Restez dans la boucle",
      meta: "Inscrivez-vous : nouveautés, ouverture des salles Action, offres, dates spéciales.",
      kw: "newsletter gamedoor 41",
      kwSec: ["newsletter escape game caen"],
      intent: "navigational",
      prio: "P2",
      silo: "utility",
      links: ["actu-action", "contact"],
    },

    /* ================================================================
       9. LÉGAL (footer)
       ================================================================ */
    {
      id: "mentions-legales",
      url: "/mentions-legales",
      title: "Mentions légales | GAMEDOOR·41",
      h1: "Mentions légales",
      meta: "Mentions légales de GAMEDOOR·41 — SARL La Boehme.",
      kw: "mentions légales gamedoor",
      kwSec: [],
      intent: "navigational",
      prio: "P2",
      silo: "legal",
      links: ["cgv", "confidentialite", "cookies"],
    },
    {
      id: "cgv",
      url: "/cgv",
      title: "CGV | GAMEDOOR·41",
      h1: "Conditions Générales de Vente",
      meta: "Conditions générales de vente — réservations, annulations, remboursements.",
      kw: "cgv escape game",
      kwSec: [],
      intent: "navigational",
      prio: "P2",
      silo: "legal",
      links: ["mentions-legales", "confidentialite"],
    },
    {
      id: "confidentialite",
      url: "/confidentialite",
      title: "Politique de confidentialité | GAMEDOOR·41",
      h1: "Confidentialité",
      meta: "Politique de confidentialité, traitement des données personnelles RGPD.",
      kw: "confidentialité gamedoor",
      kwSec: ["rgpd escape game"],
      intent: "navigational",
      prio: "P2",
      silo: "legal",
      links: ["mentions-legales", "cookies", "cgv"],
    },
    {
      id: "cookies",
      url: "/cookies",
      title: "Gestion des cookies | GAMEDOOR·41",
      h1: "Cookies",
      meta: "Politique cookies et préférences.",
      kw: "cookies gamedoor",
      kwSec: [],
      intent: "navigational",
      prio: "P2",
      silo: "legal",
      links: ["confidentialite", "mentions-legales"],
    },
    {
      id: "plan-du-site",
      url: "/plan-du-site",
      title: "Plan du site | GAMEDOOR·41",
      h1: "Plan du site",
      meta: "Toutes les pages du site GAMEDOOR·41 d'un seul coup d'œil.",
      kw: "plan site gamedoor",
      kwSec: [],
      intent: "navigational",
      prio: "P2",
      silo: "legal",
      links: ["root"],
    },

    /* ================================================================
       10. SOUS-DOMAINE EN/
       ================================================================ */
    {
      id: "en",
      url: "/en/",
      title: "GAMEDOOR·41 — Escape Room, Quiz & Events in Caen, Normandy",
      h1: "GAMEDOOR·41 — Caen's house of games",
      meta: "Four immersive game worlds under one roof in Caen, Normandy: escape rooms, live quiz, action games, premium events.",
      kw: "escape room caen",
      kwSec: ["escape game normandy", "things to do caen", "quiz caen"],
      intent: "navigational",
      prio: "P1",
      silo: "en",
      links: ["en-escape", "en-quiz", "en-events", "en-visit", "root"],
      note: "Mirror EN tree — only the high-priority pages are translated for V1 (≈12 pages).",
      children: [
        {
          id: "en-escape",
          url: "/en/escape-room",
          title: "Escape Rooms in Caen — 3 immersive rooms | GAMEDOOR·41",
          h1: "Escape Rooms in Caen",
          meta: "Three escape rooms in Caen: Psychiatric, Custody, Back to 80's. Up to 6 players, 60 minutes.",
          kw: "escape room caen",
          kwSec: ["escape room normandy", "escape game caen english"],
          intent: "commercial",
          prio: "P1",
          silo: "en",
          links: ["en-psychiatric", "en-garde-a-vue", "en-back80", "en"],
          children: [
            { id: "en-psychiatric", url: "/en/escape-room/psychiatric", title: "Psychiatric — Horror Escape Room in Caen | GAMEDOOR·41", h1: "Psychiatric", meta: "Horror escape room in Caen. 60 minutes, 2 to 6 players.", kw: "horror escape room caen", kwSec: ["scary escape room normandy"], intent: "transactional", prio: "P2", silo: "en", links: ["en-escape", "en"] },
            { id: "en-garde-a-vue", url: "/en/escape-room/custody", title: "Custody — Detective Escape Room in Caen | GAMEDOOR·41", h1: "Custody", meta: "Detective escape room in Caen. 60 minutes, 3 to 6 players.", kw: "detective escape room caen", kwSec: ["mystery escape room normandy"], intent: "transactional", prio: "P2", silo: "en", links: ["en-escape", "en"] },
            { id: "en-back80", url: "/en/escape-room/back-to-80s", title: "Back to 80's — Fun Escape Room in Caen | GAMEDOOR·41", h1: "Back to 80's", meta: "80s themed escape room in Caen. 60 minutes, 2 to 6 players.", kw: "80s escape room caen", kwSec: ["family escape room normandy"], intent: "transactional", prio: "P2", silo: "en", links: ["en-escape", "en"] },
          ],
        },
        {
          id: "en-quiz",
          url: "/en/quiz",
          title: "Live Quiz Game in Caen — Buzz Your Brain | GAMEDOOR·41",
          h1: "Live Quiz Game",
          meta: "Live buzzer quiz in Caen. Cinema, music, pop culture, 80s. From 6 to 30 players.",
          kw: "quiz caen",
          kwSec: ["live quiz normandy", "trivia caen"],
          intent: "commercial",
          prio: "P1",
          silo: "en",
          links: ["en"],
        },
        {
          id: "en-events",
          url: "/en/events",
          title: "Corporate Events & Private Parties in Caen | GAMEDOOR·41",
          h1: "Corporate & private events",
          meta: "Team building, seminars, private parties in Caen. Four game worlds, full venue privatization available.",
          kw: "team building caen english",
          kwSec: ["corporate event caen", "seminar caen normandy"],
          intent: "commercial",
          prio: "P1",
          silo: "en",
          links: ["en"],
        },
        {
          id: "en-visit",
          url: "/en/visit",
          title: "How to find us — GAMEDOOR·41 Caen",
          h1: "How to find us",
          meta: "41 bis rue Pasteur, 14120 Mondeville (Caen). 5 min from Caen city centre, free parking, tram T1.",
          kw: "gamedoor 41 address",
          kwSec: ["caen escape room location"],
          intent: "navigational",
          prio: "P1",
          silo: "en",
          links: ["en"],
        },
      ],
    },
  ],
};

/* expose to window */
window.SITEMAP = SITEMAP;
window.SILOS = SILOS;
window.INTENT_COLORS = INTENT_COLORS;
